title: "The title of your site"
description: "A short description of your site's purpose"
markdown: kramdown
remote_theme: pages-themes/dinky@v0.2.0
show_downloads: false
plugins:
- jekyll-remote-theme
